<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-26T12:53:02 IST" name="Default suite" finished-at="2025-01-26T12:53:07 IST" duration-ms="5140">
    <groups>
    </groups>
    <test started-at="2025-01-26T12:53:02 IST" name="Default test" finished-at="2025-01-26T12:53:07 IST" duration-ms="5140">
      <class name="tests.CreateOffer">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:tests.CreateOffer@76505305]" started-at="2025-01-26T12:53:02 IST" name="launchApp" finished-at="2025-01-26T12:53:07 IST" duration-ms="4881" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="createOffer()[pri:0, instance:tests.CreateOffer@76505305]" started-at="2025-01-26T12:53:07 IST" name="createOffer" finished-at="2025-01-26T12:53:07 IST" duration-ms="13" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Driver must be set]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Driver must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:64)
at org.openqa.selenium.interactions.Actions.<init>(Actions.java:67)
at org.openqa.selenium.interactions.Actions.<init>(Actions.java:63)
at webPages.Loopper.goToClothing(Loopper.java:22)
at tests.CreateOffer.createOffer(CreateOffer.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOffer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.CreateOffer@76505305]" started-at="2025-01-26T12:53:07 IST" name="tearDown" finished-at="2025-01-26T12:53:07 IST" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.CreateOffer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
